---
sudo: required
language: ruby
cache: bundler
rvm:
- 2.4.4
services:
- docker
addons:
  postgresql: '9.5'
env:
  global:
  - SERVICE_CATALOG_DATABASE_USERNAME=root
  - SERVICE_CATALOG_DATABASE_PASSWORD=smartvm
before_install:
- gem install bundler -v 1.16.4
- psql -c "CREATE USER root SUPERUSER PASSWORD 'smartvm';" -U postgres
before_script:
- bundle exec rake db:create db:migrate
deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: master
